### ISSUE TITLE
Impossible to build since github

### ISSUE THREAD

**Issue by JJarrie** [MALfunction84/psi-probe#454]
Hello,

How to build the project with the github repository? 
The pom project are link to Google Code Scm and subversion system, and the Google Code project are unreachable, have you an issue?

**Comment by MALfunction84** [comment]
Yeah, there are a lot of updates that need to happen. Issue #452 lists a few more.

**Comment by gothrek22** [comment]
Can be worked around by removing the buildnumber-maven-plugin definition from the main pom.xml
