### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by jander99** [MALfunction84/psi-probe#455]
Might want to think about using Travis CI to do build pass/fail validation.  This would take a few minutes to set up but might give normal users stopping by to grab updated code a little reassurance that things aren't broken from the migration.

**Comment by MALfunction84** [comment]
Depends on #453

**Comment by MALfunction84** [comment]
The build [fails on Travis](https://travis-ci.org/MALfunction84/psi-probe) because the of Oracle dependencies. Suggestions?

**Comment by jander99** [comment]
I made sure before replying to check the Oracle license. I doubt you're a "partner" and so therefore can't redistribute the oracle driver.  Doesn't look like there are any properties to be added to a .travis.yml that would enable Oracle Drivers, I supposed since it is not a supported database.  I guess one reason to be supported is to have the driver available.  

Guess I should have done my research before asking this.  Would have made releasing war files much easier. Darn.

**Comment by jander99** [comment]
I must not be running on all 8 cylinders today.  I found a maven repo that has ojdbc6/7 available:  https://repo.thehyve.nl/content/repositories/public/com/oracle/

Now, that might be shady, and it would require we drop Java 1.4 (I'm all for this!) for Java 1.6 or 1.7.  So this will have a dependency on a) upgrading Java to a newer (supported) version, and b) whether we want to include this repo in pom.xml.

**Comment by MALfunction84** [comment]
What about UCP?

**Comment by jander99** [comment]
It may sound backwards, but is ucp a requirement for ojdbc? I'm wondering how many times ucp is used "in the wild."  I'll see if I can find any statistics.

**Comment by MALfunction84** [comment]
UCP is a requirement for #281 to remain fixed. I'm reluctant to remove functionality.

**Comment by MALfunction84** [comment]
Maybe I can carve the Oracle things into their own Maven module and ignore it in the Travis build. Haven't found a way to do this yet.

**Comment by jander99** [comment]
I found both ojdbc6|7 and ucp on, suprisingly, The Church of Latter Day Saints.  https://code.lds.org/nexus/content/repositories/main-repo/  

From a FOSS perspective, this breaks since technically we probably shouldn't be getting the oracle driver in this fashion.  


Forgive my lack of formality on providing a pull request since I'm working on a branch for Java7, but I tried the following and it seemed to work:

Add the repo:
```xml
<repository>
    <snapshots>
        <enabled>false</enabled>
        <updatePolicy>never</updatePolicy>
    </snapshots>
    <id>code.lds.org</id>
    <name>code.lds.org</name>
    <url>https://code.lds.org/nexus/content/repositories/main-repo/</url>
    <layout>default</layout>
</repository>
```

Update the ojdbc and ucp deps:

```xml
<dependency>
    <groupId>com.oracle</groupId>
    <artifactId>ucp</artifactId>
    <version>12.1.0.2</version>
</dependency>
<dependency>
    <groupId>com.oracle</groupId>
    <artifactId>ojdbc7</artifactId>
    <version>12.1.0.2</version>
</dependency>
```

Make sure if you've manually installed the jar files to maven to remove them from your local .m2 repo.  Just delete com.oracle completely.  

Run mvn package:

You can see it pulling down the jars:
```
Downloading: https://m2proxy.atlassian.com/repository/public/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.pom
Downloading: http://download.java.net/maven/2/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.pom
Downloading: https://repository.jboss.org/nexus/content/repositories/deprecated/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.pom
Downloading: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.pom
Downloaded: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.pom (452 B at 1.1 KB/sec)
Downloading: https://m2proxy.atlassian.com/repository/public/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.pom
Downloading: http://download.java.net/maven/2/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.pom
Downloading: https://repository.jboss.org/nexus/content/repositories/deprecated/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.pom
Downloading: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.pom
Downloaded: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.pom (455 B at 3.0 KB/sec)
Downloading: https://m2proxy.atlassian.com/repository/public/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar
Downloading: https://m2proxy.atlassian.com/repository/public/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.jar
Downloading: http://download.java.net/maven/2/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.jar
Downloading: http://download.java.net/maven/2/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar
Downloading: https://repository.jboss.org/nexus/content/repositories/deprecated/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.jar
Downloading: https://repository.jboss.org/nexus/content/repositories/deprecated/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar
Downloading: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.jar
Downloading: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar
Downloaded: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ucp/12.1.0.2/ucp-12.1.0.2.jar (716 KB at 690.6 KB/sec)
Downloaded: https://code.lds.org/nexus/content/repositories/main-repo/com/oracle/ojdbc7/12.1.0.2/ojdbc7-12.1.0.2.jar (3613 KB at 850.7 KB/sec)
```
maven tries other repos before trying the lds repo and actually catching the .jar files.

**Comment by MALfunction84** [comment]
@jander99 Good find! I have my doubts about doing this, but I'm inclined to use this until it stops working.
